export const LOAD_CATEGORY_ANSWERS = 'LOAD_CATEGORY_ANSWERS';
export const GET_BY_ID = 'GET_BY_ID';
export const GET_ANSWERS_BY_QUESTION_ID = 'GET_ANSWERS_BY_QUESTION_ID';

export const ACTIVATE_ANSWER = 'ACTIVATE_ANSWER';
export const DEACTIVATE_ANSWER = 'DEACTIVATE_ANSWER';