export const LOAD_CATEGORY_QUESTIONS = 'LOAD_CATEGORY_QUESTIONS';
export const GET_BY_ID = 'GET_BY_ID';
export const GET_QUESTIONS_BY_STEP_ID = 'GET_QUESTIONS_BY_STEP_ID';

export const SET_VALUE = 'SET_VALUE';
export const FILL_VALUE = 'FILL_VALUE';
export const PREPARE_VALUE = 'PREPARE_VALUE';
export const FLUSH_VALUES = 'FLUSH_VALUES';